global:

# ====================================================================================
# User-Customizable Values Section
# Below are the values we can safely modify to customize our Dataset Generation deployment 
# ====================================================================================

  # Namespace where the Helm chart will deploy the application resources.
  namespace: 

  # (int) number of prompt-vllm's serving orbiters
  vllm_orbiter_replica: 

  # (int) number of reviewer-vllm's serving reviewer
  vllm_reviewer_replica:

  # (int) number of orbiter to work against prompt-vllm pool
  orbiter_replica:

  # (int) number of reviewer to work against reviewer-vllm pool
  reviewer_replica:

  # Access token for authenticating with a secure API or system.
  access_token: 

  # Hugging Face API token for accessing models and resources.
  # please make sure to have a pre defined secret exist in the namespace.
  hf_token:

  # Huggingface repository and file to consume.
  input_dataset_repo: 
  input_dataset_file_name: 


  # Huggingface repository file drop location.
  output_dataset_repo: 

  # the process will create a JSON file and upload it to the mantioned repository. 
  # IMPORTNANT - file name should be WITHOUT extansion
  output_dataset_file_name: 


  # (int) Max retries, when prompt failed.
  max_retry: 

  # Hugging Face model identifier for the model to be used. 
  # user can use different Model , one for prompt and other for reviewer.
  orbiter_model_hf_id: 
  reviewer_model_hf_id: 


  # (int) Maximum number of tokens that the model can generate in a single response.
  max_generation_length: 
  
  # (int) Maximum number of tokens the model can process in a single context.
  max_context_length: 

  # (float) control the amount of GPU memory allocated for the model value between 0.0.-1.0
  gpu_memory_utilization: 

  # (int): Maximum number of prompts allowed in a single batch.
  batch_size: 

  # (int) Maximum number of prompts per batch.
  queue_target_size: 
  
  #(PromptLab) project_config related.
  template_name: ""
  template_type: ""
  template_agent: ""

  #(Reviewer) Threshold for filtering or scoring responses.
  score_treshold: 

# ====================================================================================
# DO NOT MODIFY ANYTHING BELOW THIS LINE
# Changes made below this line may break the deployment or cause unexpected behavior.
# ====================================================================================

# vllm configuration section.
vllm:
  image:
    repository: images.paas.redhat.com/genie/vllm-openai
    tag: "latest"
    pullPolicy: IfNotPresent  
  resources:
    requests:
      memory:  "16Gi"   
      cpu: "2"
      gpu: 1    
    limits:
      memory: "16Gi"   
      cpu: "2"
      gpu: 1 
  service:
    type: ClusterIP
    port: 8000

# orbiter configuration section.
orbiter:
  celery_worker_concurrency: 4
  celery_worker_prefetch_count: 2
  image:
    repository: images.paas.redhat.com/genie/prompt_lab
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      memory: "2Gi"     
      cpu: "2"       
    limits:
      memory: "2Gi"     
      cpu: "2"          

# control configuration section.
control:
  landing:
    #replicaCount: 1
    celery_worker_concurrency: 1
    celery_worker_prefetch_count: 1
    image:
      repository: images.paas.redhat.com/genie/prompt_lab 
      tag: "latest"
      pullPolicy: Always

  launchpad:
    #replicaCount: 1
    image:
      repository: images.paas.redhat.com/genie/prompt_lab
      tag: "latest"
      pullPolicy: Always

  resources:
    requests:
      memory: "1Gi"     
      cpu: "1"       
    limits:
      memory: "1Gi"     
      cpu: "1"   
# reviewer configuration section.
reviewer:
  image:
    repository: images.paas.redhat.com/genie/reviewer
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      memory: "2Gi"     
      cpu: "2"       
    limits:
      memory: "2Gi"     
      cpu: "2"   
# misc configuration section.
misc:
  resources:
    requests:
      memory: "1Gi"     
      cpu: "1"       
    limits:
      memory: "1Gi"     
      cpu: "1"   
  mongodb:
    #replicaCount: 1
    image:
      repository: mongo
      tag: "latest"
      pullPolicy: IfNotPresent
    service:
      name: mongodb
      type: ClusterIP
      port: 27017
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "aws-ebs"
  rabbitmq:
    #replicaCount: 1
    image:
      repository: images.paas.redhat.com/genie/rabbitmq
      tag: "latest"
      pullPolicy: Always
    service:
      name: rabbitmq
      type: ClusterIP
      port: 5672
      managementPort: 15672