apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}-orbiter
spec:
  replicas: {{ .Values.global.vllm_orbiter_replica}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-orbiter
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-orbiter
    spec:
      
      initContainers:
      - name: wait-for-services
        image: images.paas.redhat.com/genie/ubi8:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name | upper}}
        - name: CHART_NAME
          value: {{ .Chart.Name }}
        command: 
        - sh
        - -c
        - /mnt/config/wait-for-services.sh

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /mnt/config
            readOnly: true

      volumes:
      - name: {{ .Release.Name }}-wait-for-services 
        configMap:
          name: {{ .Release.Name }}-wait-for-services
          defaultMode: 0755  

      containers:
      - name: {{ .Chart.Name }}-orbiter
        image: "{{.Values.image.repository}}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 3000000; done;" ]
        args: [
              "--model", "{{.Values.global.orbiter_model_hf_id}}",
              {{- range .Values.global.vllm_orbiter_args }}
              '{{ . }}',
              {{- end }}
           ]
        env:
        - name: TRANSFORMERS_CACHE
          value: "/tmp/.cache"
        - name: HF_HOME
          value: "/tmp/.cache"   
        - name: VLLM_CONFIG_ROOT
          value: "/tmp/.cache"     
        - name: VLLM_CACHE_ROOT
          value: "/tmp/.cache"                    
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token

        resources:
          requests:
            memory: {{.Values.resources.requests.memory}} 
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.resources.requests.gpu}}
          limits:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.resources.requests.gpu}}
          
        ports:
          - containerPort: 8000
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5


      securityContext:
        seccompProfile:
          type: RuntimeDefault