apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-reviewer
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}-reviewer
spec:
  replicas: {{ .Values.global.vllm_reviewer_replica}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-reviewer
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-reviewer
    spec:
      
      initContainers:
      - name: wait-for-services
        image: quay.io/quay/busybox:latest
        command: 
        - sh
        - -c
        - |
          cp /config/wait-for-services.sh /tmp/wait-for-services.sh
          chmod +x /tmp/wait-for-services.sh
          /tmp/wait-for-services.sh

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /config
      volumes:
      - name: {{ .Release.Name }}-wait-for-services  
        configMap:
          name: {{ .Release.Name }}-wait-for-services

      containers:
      - name: {{ .Chart.Name }}-reviewer
        image: "{{.Values.image.repository}}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 3000000; done;" ]
        args: [
              "--model", "{{.Values.global.reviewer_model_hf_id}}",
              "--max_model_len={{.Values.global.max_context_length}}",
              "--gpu_memory_utilization={{.Values.global.gpu_memory_utilization}}"
            ]
        env:
        - name: TRANSFORMERS_CACHE
          value: "/tmp/.cache"
        - name: HF_HOME
          value: "/tmp/.cache"   
        - name: VLLM_CONFIG_ROOT
          value: "/tmp/.cache"     
        - name: VLLM_CACHE_ROOT
          value: "/tmp/.cache"                    
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token
        - name: REVIEWER_MODEL_HF_ID
          value: "{{.Values.global.reviewer_model_hf_id}}"

        resources:
          requests:
            memory: {{.Values.resources.requests.memory}} 
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.resources.requests.gpu}}
          limits:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.resources.requests.gpu}}
          
        ports:
          - containerPort: 8000
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5


      securityContext:
        seccompProfile:
          type: RuntimeDefault