apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
spec:
  type: {{.Values.service.type}}
  ports:
    - name: vllm-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
