apiVersion: v2
appVersion: v0.5.4
description: 'A Helm chart for deploying vLLM. vLLM is a fast and easy-to-use library
  for LLM inference and serving. '
home: https://substratus.ai
keywords:
- LLM
- vLLM
- AI
maintainers:
- email: sammiestoel@gmail.com
  name: samos123
  url: https://www.linkedin.com/in/samstoelinga/
name: vllm
type: application
version: 0.5.5
