""" 
LLM question:
I have a LLM model server by some application. The model where fine-tuned with certain project code base.

My purpose now is to add context for each user question to enrich the LLM model context-awareness where the goal is to provide more accurate outputs by the model. 
Assuming I have a lot of code data such Classes/Functions that generated by python parser that I already created, I want to first convert the code to text by open-source highly used library, chunk it and then embed it with open-source well known libraries as well, than add the data into vector data base such as  Postgres or any other well recommended vector database in order to be able later on to retrieve the relevant data and add it as a context to each user-question provided to my LLM model.

Can you write for me the code that taking the steps I describe above without the retrieval part just all the embeddings and entering the data to a DB?
Please use open-source well used libraries and write professional and generic code and libraries that are highly used with RAG concept, the same as my need. 
"""

# The following code use transformers for embedding, faiss for handling vector indexing, and psycopg2 for inserting data into a PostgreSQL database.
# This code outlines a RAG (retrieval-augmented generation) concept, where code embeddings are stored in a database, later to be retrieved and used as context for user queries.

# Libraries Used:
# Transformers (Huggingface): for embedding code into dense vectors.
# Faiss: for vector indexing (optional in your case, since you're storing embeddings in Postgres).
# Psycopg2: for interacting with a PostgreSQL database.

# pip install transformers
# pip install torch 
# pip install faiss-cpu
# pip install psycopg2-binary

""" PostgreSQL Instllation Steps """
# sudo dnf update
# sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
# sudo dnf -qy module disable postgresql
# sudo dnf install -y postgresql15 postgresql15-server
# sudo /usr/pgsql-15/bin/postgresql-15-setup initdb
# sudo systemctl enable --now postgresql-15

# To allow password-based authentication for PostgreSQL, edit the pg_hba.conf file. It’s typically located in /var/lib/pgsql/15/data/pg_hba.conf.
# Original Line: host    all             all             127.0.0.1/32            ident
# New Line:      host    all             all             127.0.0.1/32            md5

# sudo systemctl restart postgresql-15
# sudo su - postgres
# psql
# ALTER USER postgres PASSWORD 'your_password';
# \q
# createdb code_embeddings
# Verification: sudo systemctl status postgresql-15

""" PostgreSQL data check """
# psql -U postgres -d code_embeddings
# \dt (list tables)
# SELECT * FROM code_embeddings LIMIT 10; (view the data)
# SELECT COUNT(*) FROM code_embeddings;
# \q

# Example Flow:
"""
$ psql -U postgres -d your_db
your_db=# \dt
                 List of relations
 Schema |      Name      | Type  |  Owner
--------+----------------+-------+----------
 public | code_embeddings | table | postgres
(1 row)

your_db=# SELECT * FROM code_embeddings LIMIT 10;
 id | chunk | embedding
----+-------+-----------
(0 rows)  -- Example output, showing your data

your_db=# SELECT COUNT(*) FROM code_embeddings;
 count
-------
   100
(1 row)

your_db=# \q
"""

from transformers import AutoTokenizer, AutoModel
import torch
import psycopg2

import faiss
import numpy as np

def chunk_code(code_text, max_chunk_size=512):
    words = code_text.split()
    chunks = []
    current_chunk = []
    
    for word in words:
        current_chunk.append(word)
        if len(current_chunk) >= max_chunk_size:
            chunks.append(' '.join(current_chunk))
            current_chunk = []
    
    if current_chunk:
        chunks.append(' '.join(current_chunk))
    
    return chunks

# Use a pre-trained model from transformers to convert text chunks into embeddings.
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')

def embed_text(text_chunks):
    embeddings = []
    for chunk in text_chunks:
        inputs = tokenizer(chunk, return_tensors='pt', padding=True, truncation=True, max_length=512)
        with torch.no_grad():
            outputs = model(**inputs)
        embeddings.append(outputs.last_hidden_state.mean(dim=1).squeeze().numpy())  # Pool the embedding
    return embeddings

def index_embeddings(embeddings):
    dimension = len(embeddings[0])  # Dimension of the embeddings
    index = faiss.IndexFlatL2(dimension)  # L2 similarity

    # Convert embeddings to np.array and add to index
    np_embeddings = np.array(embeddings).astype('float32')
    index.add(np_embeddings)
    
    return index

def insert_into_postgres(embeddings, chunks, db_params):
    conn = psycopg2.connect(**db_params)
    cur = conn.cursor()

    # Assuming a table structure with id, chunk, embedding
    cur.execute("""
        CREATE TABLE IF NOT EXISTS code_embeddings (
            id SERIAL PRIMARY KEY,
            chunk TEXT,
            embedding FLOAT8[]
        )
    """)
    
    for chunk, embedding in zip(chunks, embeddings):
        cur.execute("""
            INSERT INTO code_embeddings (chunk, embedding) 
            VALUES (%s, %s)
        """, (chunk, embedding.tolist()))
    
    conn.commit()
    cur.close()
    conn.close()

def process_and_store_code(code_text, db_params):
    # Step 1: Chunk the code
    chunks = chunk_code(code_text)

    # Step 2: Embed the chunks
    embeddings = embed_text(chunks)

    # Step 3: Index the embeddings (Optional if you're using FAISS locally)
    index = index_embeddings(embeddings)
    
    print(embeddings)
    print('----')
    print(chunks)
    # Step 4: Insert into PostgreSQL
    # insert_into_postgres(embeddings, chunks, db_params)

code_text = """class MyClass:
    def my_function():
        # Your code here
"""

# Database connection parameters
db_params = {
    'dbname': 'code_embeddings',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',
    'port': 5432,
}

process_and_store_code(code_text, db_params)