[supervisord]
nodaemon=true

[program:celery]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && celery -A celery_app.init worker --loglevel=info --concurrency=1"
priority=10
autostart=true
autorestart=true
startretries=3

[program:celery-beat]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && celery -A celery_app.init beat --loglevel=info"
priority=10
autostart=true
autorestart=true
startretries=3

[program:app]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && python app.py"
priority=20
autostart=true
autorestart=true
startretries=3
