apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
    haproxy.router.openshift.io/rewrite-target: /
  labels:
    {{- include "genie-ui.labels" . | nindent 4 }}
  name: {{ include "genie-ui.fullname" . }}
spec:
  host: 
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "genie-ui.fullname" . }}
    weight: 100
  wildcardPolicy: None

