apiVersion: v1
kind: Service
metadata:
  name: {{ include "genie-ui.fullname" . }}
  labels:
    {{- include "genie-ui.labels" . | nindent 4 }}
spec:
        #type: {{ .Values.service.type }}
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      #nodePort: 32035
      nodePort: {{ .Values.service.nodeport }}
      targetPort: 443
      protocol: TCP
      name: http
      #- port: 443
      #nodePort: 32036
      #targetPort: 443
      #protocol: TCP
      #name: https
  selector:
    {{- include "genie-ui.selectorLabels" . | nindent 4 }}
