apiVersion: v1
kind: Service
metadata:
  name: {{ include "genie-ui.fullname" . }}
  labels:
    {{- include "genie-ui.labels" . | nindent 4 }}
spec:
  ports:
    #- port: 8080
    #  targetPort: 8080
    - port: 8080
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "genie-ui.selectorLabels" . | nindent 4 }}
