apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.orbiter_replica }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
      
      initContainers:
      - name: validate-vllm-orbiter-readiness
        image: registry.redhat.io/openshift4/ose-cli
        env:
        - name: KUBECONFIG
          value: /tmp/kubeconfig
        - name: TOKEN
          value: {{.Values.global.access_token}}
        - name: NAMESPACE
          value: {{.Values.global.namespace}}
        - name: RELEASE_NAME
          value: {{.Release.Name}}
        - name: CHART_NAME
          value: vllm-{{ .Chart.Name }}

        command:
        - sh
        - -c
        - |
          cp /config/wait-for-deployment.sh /tmp/wait-for-deployment.sh
          chmod +x /tmp/wait-for-deployment.sh
          /tmp/wait-for-deployment.sh $CHART_NAME
        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-deployment
            mountPath: /config

      - name: wait-for-services
        image: quay.io/quay/busybox:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name| upper}}
        - name: CHART_NAME
          value: {{ .Chart.Name | upper }}

        command: 
        - sh
        - -c
        - |
          cp /config/wait-for-services.sh /tmp/wait-for-services.sh
          chmod +x /tmp/wait-for-services.sh
          /tmp/wait-for-services.sh

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /config

      volumes:
      - name: {{ .Release.Name }}-wait-for-deployment
        configMap:
          name: {{ .Release.Name }}-wait-for-deployment
      - name: {{ .Release.Name }}-wait-for-services
        configMap:
          name: {{ .Release.Name }}-wait-for-services
          
      containers:        
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        command: 
        - sh
        - -c
        - |
          promptlab orbiter --celery --reviewer --celery-worker-concurrency {{.Values.celery_worker_concurrency}} --celery-worker-prefetch-count {{.Values.celery_worker_prefetch_count}}

        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 3000000; done;" ]

        env:
        - name: HF_HOME
          value: "/tmp/.cache"  
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token
        - name: PROMPT_LAB_MODEL_HF_ID
          value: "{{.Values.global.orbiter_model_hf_id}}"
        - name: PROMPT_LAB_MAX_GENERATION_LENGTH
          value: "{{.Values.global.max_generation_length}}"
        - name: PROMPT_LAB_MAX_CONTEXT_LENGTH
          value: "{{.Values.global.max_context_length}}"
        - name: CELERY_WORKER_CONCURRENCY
          value: "{{.Values.celery_worker_concurrency}}"
        - name: CELERY_WORKER_PREFETCH_COUNT
          value: "{{.Values.celery_worker_prefetch_count}}"
        

        - name: RABBITMQ_IP
          value: $({{ .Release.Name | upper }}_RABBITMQ_SERVICE_HOST)
        - name: RABBITMQ_PORT
          value: $({{ .Release.Name | upper }}_RABBITMQ_SERVICE_PORT)
        - name: MONGODB_IP
          value: $({{ .Release.Name | upper }}_MONGODB_SERVICE_HOST)
        - name: MONGODB_PORT
          value: $({{ .Release.Name | upper }}_MONGODB_SERVICE_PORT)
        - name: MODEL_API_URL
          value: "http://$({{ .Release.Name | upper }}_VLLM_ORBITER_SVC_SERVICE_HOST):$({{ .Release.Name | upper }}_VLLM_ORBITER_SVC_SERVICE_PORT)/v1/completions"


        resources:
          requests:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
          limits:
            memory: {{.Values.resources.limits.memory}}
            cpu: {{.Values.resources.limits.cpu}}

      securityContext:
        seccompProfile:
          type: RuntimeDefault