from typing import List
from prompt import PromptGenerator, PromptMaxTokenSizeFailPolicy, PromptCompositePolicy
from batch import BatchMaxPromptsNumberStrategy, BatchMaxTokenStrategy, BatchCompositeStrategy, Batch
from utils.celery.celery import is_queue_full, send_task
from utils.tokenizer import TokenizerUtils
from storage import DataRepository
import time


class PromptPreparation:
    """
    Handles the enqueuing of prompts into a processing queue.

    Responsibilities:
      - Iterates over a `PromptGenerator` to fetch the next prompt.
      - Uses a `Batch` to manage prompts, applying skip policies and batch strategies.
      - Submits batches to the specified queue when full or upon completion.

    Attributes:
      - repository: Source of data for prompt generation and progress tracking.
      - tokenizer: Utility for tokenization and token limit management.
      - batch_strategies: A composite of strategies to control batching behavior.
      - skip_policies: A composite of policies to determine whether prompts should be skipped.
      - queue_target_size: Maximum size of the queue before pausing submissions.
      - prompts_queue_name: Name of the queue to which prompts are submitted.
      - prompt_query_task_name: Celery task name used for batch submission.
      - generator: An instance of `PromptGenerator` for prompt generation.
      - batch: A collection of prompts managed according to strategies and policies.
      - processed_uuids: Set of UUIDs representing already-processed prompts.
    """

    def __init__(
            self,
            repository: DataRepository,
            tokenizer: TokenizerUtils,
            queue_target_size: int,
            prompts_queue_name: str,
            batch_size: int = 8,
            prompt_query_task_name: str = "fetch_prompts_batch"
    ):
        """
        Initializes the PromptEnqueue instance.

        Args:
            repository: Data source for generating and tracking prompts.
            tokenizer (TokenizerUtils): Utility for handling tokenization constraints.
            batch_strategies (List[BatchStrategy]): List of strategies to control batch behavior.
            fail_policies (List[SkipPolicy]): List of policies to determine prompt skipping.
            queue_target_size (int): Maximum queue size before submission pauses.
            prompts_queue_name (str): The name of the queue where prompts are submitted.
            prompt_query_task_name (str): Celery task name for batch submission. Default is "fetch_prompts_batch".
        """
        self.repository = repository
        self.tokenizer = tokenizer
        self.prompt_query_task_name = prompt_query_task_name
        self.batch_size = batch_size

        self.queue_target_size = queue_target_size
        self.prompts_queue_name = prompts_queue_name

        self.generator = PromptGenerator(self.repository, self.tokenizer)
        self.prepared_prompts_batch = Batch(
            batch_strategies=BatchCompositeStrategy([BatchMaxTokenStrategy(self.tokenizer.get_tokens_limit()),
                                                     BatchMaxPromptsNumberStrategy(self.batch_size)]),
            prompt_policies=PromptCompositePolicy([
                PromptMaxTokenSizeFailPolicy(self.tokenizer.get_tokens_limit())
            ]))

        # Track processed prompts using UUIDs
        self.processed_uuids = self.repository.load_processed_prompts_uuids()

        print("[PromptEnqueue] Initialized.")

    def run(self):
        """
        Main loop for processing and submitting prompts.

        Workflow:
            - Iterates through prompts generated by the `PromptGenerator`.
            - Adds prompts to the batch if they pass the skip policies.
            - Submits the batch to the queue when full.
            - Handles leftover prompts after the loop finishes.
        """
        for prompt in self.generator:
            if prompt.uuid in self.processed_uuids:
                # Skip already processed prompts
                continue
            self.repository.update_prompt_generation_counter()

            added = self.prepared_prompts_batch.add_prompt(prompt)
            if not added:
                # Submit the current batch if full
                if self.prepared_prompts_batch.has_prompts():
                    self._submit_current_batch()

                # check if the batch that didn't apply to batch strategy failed, if not add to new batch
                if not prompt.is_failed:
                    self.prepared_prompts_batch.add_prompt(prompt)
                else:
                    self.repository.save_fail_prompts([prompt.to_dict()])

        # Submit remaining prompts
        if self.prepared_prompts_batch.has_prompts():
            self._submit_current_batch()

    def _submit_current_batch(self):
        """
        Finalizes and submits the current batch of prompts to the queue.

        Handles:
            - Checking if the queue is full before submission.
            - Waiting if the queue is full and retrying periodically.
            - Sending the batch as a task to the Celery queue.
        """
        finalized_prompts = self.prepared_prompts_batch.to_dict()
        self.prepared_prompts_batch.finalize_batch()

        if not finalized_prompts:
            return

        while is_queue_full(queue_name=self.prompts_queue_name, queue_target_size=self.queue_target_size):
            # Queue is full; wait before retrying
            time.sleep(5)

        send_task(self.prompt_query_task_name, celery_queue=self.prompts_queue_name, batch=finalized_prompts)

        print(f"[PromptEnqueue] Submitted {len(finalized_prompts)} prompts to queue {self.prompts_queue_name}.")
