apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        runAsUser: 1004200000
        runAsGroup: 1004200000
        fsGroup: 1004200000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }} 
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "mongod --bind_ip_all --dbpath /data/db" ]
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        
        readinessProbe:
          tcpSocket:
            port: 27017  
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 27017 
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db

      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb-pvc
          
      securityContext:
        runAsUser: 1004200000
        seccompProfile:
          type: RuntimeDefault