apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-np
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-np

  policyTypes:
    - Ingress
  ingress:
    - ports:
      - port: 27017
        protocol: TCP
    - ports:
      - port: 15672
        protocol: TCP