apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
  selector:
    app: {{ .Release.Name }}-rabbitmq