apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rabbitmq.service.port }}
        - containerPort: {{ .Values.rabbitmq.service.managementPort }}

        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
      
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}




          