apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-mongodb-route
  namespace: {{ .Values.global.namespace }}
  labels:
    paas.redhat.com/appcode: TAG-001
  annotations:
    openshift.io/host.generated: "true"
spec:
  host: 
  port:
    targetPort: {{ .Values.mongodb.service.port }}
  to:
    kind: Service
    name: {{ .Release.Name }}-mongodb
    weight: 100
  wildcardPolicy: None

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-rabbitmq-route
  namespace: {{ .Values.global.namespace }}
  labels:
    paas.redhat.com/appcode: TAG-001
  annotations:
    openshift.io/host.generated: "true"
spec:
  host: 
  port:
    targetPort: {{ .Values.rabbitmq.service.managementPort }}
  to:
    kind: Service
    name: {{ .Release.Name }}-rabbitmq
    weight: 100
  wildcardPolicy: None