import logging
import os
from flask import request, Blueprint
from flask import jsonify, Response
from webargs import fields
from helpers.apiargs import Fields, from_query, from_body
from be_utils.utils import json_response
from rag.providers.rag_backend import parsed_elements_metadata_expansion, query_meta_data_retrieval

rag_bp = Blueprint("rag", __name__)

@rag_bp.route("/", methods=["GET"])
def sanity_check():
    return 'There is access to API RAG Backend\n'

@rag_bp.route("/registerNewProject", methods=["GET"])
@from_body({"parsed_elements_location":      fields.Str(missing='', data_key="parsedElementsLocation"),
             "project_name":                  fields.Str(missing='', data_key="projectName"),
             "project_repo_path":             fields.Str(missing='', data_key="projectRepoPath"),
             "naming_mapping":                fields.Dict(missing={}, data_key="namingMapping"),
             "built_in_keys":                 fields.List(fields.Str(), missing=[], data_key="builtInKeys"),
             "exclude_types":                 fields.List(fields.Str(), missing=[], data_key="excludeTypes"),
             "project_programming_languages": fields.List(fields.Str(), missing=[], data_key="projectProgrammingLanguages"),
})
def register_new_project(parsed_elements_location, project_name, project_repo_path, naming_mapping, built_in_keys, exclude_types, project_programming_languages):
    """map new project parsed elements with relevant metdata, add all of the expanded elements to new DB collection

    :param str parsed_elements_location: representing file location of where the dedicated project parsed elements are located (generated by the parser)
    :param str project_name:
    :param str project_repo_path: git repository link of the dedicated project
    :param dict naming_mapping: key:value naming for each parsed object metdata (which will be saved in dedicated DB collection)
    :param list built_in_keys: what are all the default keys reside under the parsed objects which we will map to the metadata
    :param list exclude_types: what are all the "elements_types" of the different parsed objects which we don't want to map
    :param list project_programming_languages: what are the programming languages being used in the git repo for the dedicated project 
    :return:
    """
    parsed_elements_metadata_expansion(parsed_elements_location, project_name, project_repo_path, naming_mapping, built_in_keys, exclude_types, project_programming_languages)
    return json_response({"result": "metadata added successfully for each of the parsed elements\n"})

@rag_bp.route("/queryRetrieval", methods=["GET"])
@from_body({"text":                           fields.Str(missing='', data_key="text"),
            "project_name":                   fields.Str(missing='', data_key="projectName"),
            "model_name":                     fields.Str(missing='', data_key="modelName"),
            "model_id":                       fields.Str(missing='', data_key="modelId"),
})
def query_retrieval(text, project_name, model_name, model_id):
    """retrieving best matched elements baed on the user query for specific project

    :param str text: user query for the LLM
    :param str project_name:
    :param str project_repo_path: git repository link of the dedicated project
    :param str model_name: current model name which being served by VLLM
    :param str model_id: current model id which being served by VLLM
    :return:
    """
    best_match = query_meta_data_retrieval(text, project_name, model_name, model_id)
    return json_response({"result": best_match})