apiVersion: v2
name: reviewer
description: reviewer chart will create a Pods communicate reviewer with VLLM service.

type: application
version: 0.1.0
appVersion: "1.16.0"
dependsOn:
  - name: misc
    version: "1.16.0"