global:
  namespace: 
  reviewer_replica: 
  model_hf_id: 
  max_generation_length: ""
  max_context_length: ""
  gpu_memory_utilization: ""
  batch_size: ""
  score_treshold: ""

image:
  repository: 
  tag: 
  pullPolicy: 

resources:
  requests:
    memory:     
    cpu:     
  limits:
    memory:     
    cpu:   
