apiVersion: v1
kind: Service
metadata:
  name: {{ include "genie-llm-be.fullname" . }}
  labels:
    {{- include "genie-llm-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
          #- port: {{ .Values.service.port }}
    - port: 80
      nodePort: {{ .Values.service.socket_nodeport }}
      targetPort: 5001
      protocol: TCP
      name: httpsocket
    - port: 8080
      nodePort: {{ .Values.service.http_nodeport }}
      targetPort: 5050
      protocol: TCP
      name: http

  selector:
    {{- include "genie-llm-be.selectorLabels" . | nindent 4 }}
