global:
  namespace: 

  vllm_orbiter_replica: 
  vllm_reviewer_replica:

  orbiter_model_hf_id:
  reviewer_model_hf_id:

  vllm_orbiter_args:
  vllm_reviewer_args:

image:
  repository: images.paas.redhat.com/genie/vllm-openai
  tag: "latest"
  pullPolicy: IfNotPresent  

resources:
  requests:
    memory:  "46Gi"   
    cpu: "2"
    gpu: 1    
  limits:
    memory: "4Gi"   
    cpu: "2"
    gpu: 1  

service:
  type: ClusterIP
  port: 8000