env:
  MONGODB_IP: mongodb
  MONGODB_PORT: 27017
  RABBITMQ_IP: rabbitmq
  RABBITMQ_PORT: 5672
  QDRANT_URL: "http://qdrant"
  QDRANT_PORT: 6333
  BACKEND_ENV: "production"
  ROLE: "flask"
debug: false

# replicaCount: 1
image:
   repository: images.paas.redhat.com/genie/unifai/unifai-dataflow
   tag: latest
   pullPolicy: Always

service:
  type: ClusterIP
  port: 13456


volumes:
  - name: unifai-dataflow-shared-storage
    persistentVolumeClaim:
      claimName: unifai-dataflow-shared-storage

volumeMounts:
  - name: unifai-dataflow-shared-storage
    mountPath: /app/shared

livenessProbe:
  httpGet:
    path: /api/slack/
    port: 13456
readinessProbe:
  httpGet:
    path: /api/slack/
    port: 13456

resources:
  limits:
    cpu: 4
    memory: 12Gi
  requests:
    cpu: 4
    memory: 12Gi
