apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{.Values.global.namespace}}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.reviewer_replica }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        runAsUser: 1004200000
      
      initContainers:
      - name: validate-vllm-reviewer-readiness
        image: registry.redhat.io/openshift4/ose-cli
        env:
        - name: KUBECONFIG
          value: /tmp/kubeconfig
        - name: TOKEN
          value: {{.Values.global.access_token}}
        - name: NAMESPACE
          value: {{.Values.global.namespace}}
        - name: RELEASE_NAME
          value: {{.Release.Name}}
        - name: CHART_NAME
          value: vllm-{{ .Chart.Name }}

        command:
        - sh
        - -c
        - |    
          cp /config/wait-for-deployment.sh /tmp/wait-for-deployment.sh
          chmod +x /tmp/wait-for-deployment.sh
          /tmp/wait-for-deployment.sh $CHART_NAME
        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-deployment
            mountPath: /config

      - name: wait-for-services
        image: quay.io/quay/busybox:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name | upper}}
        - name: CHART_NAME
          value: {{ .Chart.Name | upper}}
        command: 
        - sh
        - -c
        - |
          cp /config/wait-for-services.sh /tmp/wait-for-services.sh
          chmod +x /tmp/wait-for-services.sh
          /tmp/wait-for-services.sh

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /config

      volumes:
      - name: {{ .Release.Name }}-wait-for-deployment
        configMap:
          name: {{ .Release.Name }}-wait-for-deployment
      - name: {{ .Release.Name }}-wait-for-services
        configMap:
          name: {{ .Release.Name }}-wait-for-services

      containers:    
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        args: ["reviewer"]
        env:
        - name: TRANSFORMERS_CACHE
          value: "/tmp"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token
        - name: REVIEWER_MODEL_HF_ID
          value: "{{.Values.global.reviewer_model_hf_id}}"
        - name: REVIEWER_MAX_GENERATION_LENGTH
          value: "{{.Values.global.max_generation_length}}"
        - name: REVIEWER_MAX_CONTEXT_LENGTH
          value:  "{{.Values.global.max_context_length}}"
        - name: REVIEWER_BATCH_SIZE
          value:  "{{.Values.global.batch_size}}"
        - name: REVIEWER_SCORE_THRESHOLD 
          value:  "{{.Values.global.score_treshold}}"

        - name: RABBITMQ_IP
          value: $({{ .Release.Name | upper }}_RABBITMQ_SERVICE_HOST)
        - name: RABBITMQ_PORT
          value: $({{ .Release.Name | upper }}_RABBITMQ_SERVICE_PORT)
        - name: MONGODB_IP
          value: $({{ .Release.Name | upper }}_MONGODB_SERVICE_HOST)
        - name: MONGODB_PORT
          value: $({{ .Release.Name | upper }}_MONGODB_SERVICE_PORT)
        - name: VLLM_IP
          value: $({{ .Release.Name | upper }}_VLLM_REVIEWER_SVC_SERVICE_HOST)
        - name: VLLM_PORT
          value: $({{ .Release.Name | upper }}_VLLM_REVIEWER_SVC_SERVICE_PORT)

        resources:
          requests:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
          limits:
            memory: {{.Values.resources.limits.memory}}
            cpu: {{.Values.resources.limits.cpu}}

      securityContext:
        runAsUser: 1004200000
        seccompProfile:
          type: RuntimeDefault