apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wait-for-services
  namespace: {{ .Values.global.namespace }}
data:
  wait-for-services.sh: |

    while ! nc -z ${{ .Release.Name | upper }}_RABBITMQ_SERVICE_HOST ${{ .Release.Name | upper }}_RABBITMQ_SERVICE_PORT; do
    echo "Waiting for RabbitMQ service to be ready...";
      sleep 5;
    done;
    echo "RabbitMQ service ${{ .Release.Name | upper }}_RABBITMQ_SERVICE_HOST:${{ .Release.Name | upper }}_RABBITMQ_SERVICE_PORT is up!"

    
    while ! nc -z ${{ .Release.Name | upper }}_MONGODB_SERVICE_HOST ${{ .Release.Name | upper }}_MONGODB_SERVICE_PORT; do
      echo "Waiting for MongoDB service to be ready...";
      sleep 5;
    done;
    echo "MongoDB service ${{ .Release.Name | upper }}_MONGODB_SERVICE_HOST:${{ .Release.Name | upper }}_MONGODB_SERVICE_PORT is up!"

    if [ "$CHART_NAME" == "ORBITER" ] || [ "$CHART_NAME" == "REVIEWER" ]; then
      SERVICE_URL="${RELEASE_NAME}_VLLM_${CHART_NAME}_SVC_SERVICE_HOST"
      SERVICE_PORT="${RELEASE_NAME}_VLLM_${CHART_NAME}_SVC_SERVICE_PORT"

      SERVICE_HOST=$(eval echo \$$SERVICE_URL)
      SERVICE_PORT_VAL=$(eval echo \$$SERVICE_PORT)
     
      while ! nc -z $SERVICE_HOST $SERVICE_PORT_VAL; do
          echo "waiting for http://$SERVICE_HOST:$SERVICE_PORT_VAL service..."
          sleep 5
      done
      echo "service http://$SERVICE_HOST:$SERVICE_PORT_VAL is up!"
    fi