debug: false
env: 
  BE_URL: genie-be:8080
  LLM_BE_URL: genie-llm-be:8080

image:
   repository: images.paas.redhat.com/genie/ui
   tag: 2025.01.31
service:
  type: ClusterIP

networkPolicy:
  ## Ingress and Egress policies
   ingress: 
   - ports:
      - port: 8080
        protocol: TCP
   egress: {}
  
