image:
   repository: images.paas.redhat.com/genie/ui
   tag: 2025.01.16
networkPolicy:
  ## Ingress and Egress policies
   ingress: 
   - ports:
      - port: 8080
        protocol: TCP
   egress: {}
  
