helmDefaults:
    createNamespace: false
    wait: false

releases:
  - name: unifai-mongodb
    chart: ./mongodb
    wait: true
    timeout: 300
    values:
      - "./mongodb.yaml"

  - name: unifai-qdrant
    chart: ./qdrant
    wait: true
    timeout: 300
    values:
      - "./qdrant.yaml"
      
  - name: unifai-rabbitmq
    chart: ./rabbitmq
    wait: true
    values:
      - "./rabbitmq.yaml"

