#podman run -dt -v .:/helm/charts -v ~/.kube/:/helm/.kube --name helmfile ghcr.io/helmfile/helmfile:latest bash

helmDefaults:
    createNamespace: false
    wait: true
  
releases:
  - name: genie-rabbitmq
    namespace: tag-ai--gzhou-nb
    chart: ./rabbitmq
    values:
      - "./rabbitmq.values.yaml"
  - name: genie-mongodb
    namespace: tag-ai--gzhou-nb
    chart: ./mongodb
    wait: true
    values:
      - "./mongodb.values.yaml"
  - name: genie-vllm
    namespace: tag-ai--gzhou-nb
    chart: ./vllm
    wait: true
    values:
      - "./vllm.values.yaml"
  - name: genie-ui
    namespace: tag-ai--gzhou-nb
    chart: ./genie-ui
    version: "0.9.0"
    wait: true
    values:
      - "./genie-ui.values.yaml"
  - name: genie-be
    namespace: tag-ai--gzhou-nb
    chart: ./genie-be
    wait: true
    values:
      - "genie-be.values.yaml"
  - name: genie-reviewer
    namespace: tag-ai--gzhou-nb
    chart: ./genie-reviewer
    wait: true
    values:
      - "./genie-reviewer.values.yaml"
  - name: genie-prompt-lab
    namespace: tag-ai--gzhou-nb
    chart: ./genie-prompt-lab
    wait: true
    values:
      - "./genie-prompt-lab.values.yaml"
