# Default values for mongodb.

nameOverride: ""
fullnameOverride: "mongodb"
## Additional labels for Deployment or StatefulSet
customLabels: {}
## Additional annotations for Deployment or StatefulSet
customAnnotations: {}
securityContext: {}
image:
  registry: "images.paas.redhat.com/genie"
  repository: "mongo"

