env:
  MONGODB_IP: mongodb
  MONGODB_PORT: 27017
  RABBITMQ_IP: rabbitmq
  RABBITMQ_PORT: 5672
  BACKEND_ENV: "production"
  ROLE: "celery"
  CELERY_QUEUES: "slack_queue,docs_queue"
  CELERY_WORKER: 4
debug: false

# replicaCount: 1
image:
   repository: images.paas.redhat.com/genie/unifai/unifai-dataflow
   tag: latest
   pullPolicy: Always

service:
  enabled: false

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - "timeout 2 bash -c '</dev/tcp/$RABBITMQ_IP/$RABBITMQ_PORT'"
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "timeout 2 bash -c '</dev/tcp/$RABBITMQ_IP/$RABBITMQ_PORT'"
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi
