---
- name: Deploy containers on VMs
  hosts: all
  gather_facts: no
  vars:
    rabbitmq_image: docker.io/library/rabbitmq:4.0-management
    mongodb_image: docker.io/mongodb/mongodb-community-server:latest
    registry_user: rh-ee-yhabushi
    registry_password: oWbeT+YQOEcDPo+rVOsPqtFHBPV6fIZk/mkcMtpMWR4wxBPcR1P2t5IoJ+ChzkSZ
    file_to_copy: /home/instruct/parser.json
    rabbitmq_port: "{{ RABBITMQ_PORT }}"
    hf_token: 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
    model_name: meta-llama/Llama-3.1-8B-Instruct
    max_model_len: 16384

  tasks:
    - name: Install Hugging Face CLI
      pip:
        name: huggingface_hub
        state: latest

    - name: Login to Hugging Face CLI
      shell: huggingface-cli login --token {{ hf_token }}
      register: huggingface_login
      ignore_errors: yes

    - name: Install vllm with pip
      pip:
        name: vllm
        state: latest
      register: vllm_install

    - name: Start VLLM server in a tmux session
      shell: |
        tmux new-session -d -s vllm_server "vllm serve {{ model_name }} --port 8000 --max-model-len {{ max_model_len }}"
      register: vllm_server

    - name: Verify VLLM server health endpoint
      uri:
        url: "http://0.0.0.0:8000/health"
        return_content: no
        status_code: 200
      retries: 10
      delay: 10
      register: vllm_health_check
      until: vllm_health_check.status == 200

    - name: RabbitMQ
      when: "'controller' in group_names"
      block:
        - name: Kill unneeded service
          become: yes
          command: >
            sudo systemctl stop showroom.service

        - name: Stop and remove RabbitMQ container if it exists$
          shell: |
            if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w rabbitmq; then
              podman rm -f rabbitmq;
            else
              echo "RabbitMQ container does not exist.";
            fi

        - name: Run RabbitMQ Container
          command: >
            podman run -d --name rabbitmq -h rabbitmq -p {{ rabbitmq_port }}:5672 -p 15672:15672 {{ rabbitmq_image }}


        - name: Wait for RabbitMQ container to be running
          shell: podman ps | grep rabbitmq
          register: rabbitmq_container
          retries: 5
          delay: 5
          until: rabbitmq_container.rc == 0

        - name: Check RabbitMQ application status
          shell: podman exec rabbitmq rabbitmqctl status
          register: rabbitmq_status
          retries: 5
          delay: 10
          until: rabbitmq_status.rc == 0

        - name: Display RabbitMQ port check result
          debug:
            msg: "RabbitMQ is up and listening on port 443"

        - name: Add RabbitMQ user name
          command: >
            podman exec -d rabbitmq bash -c 'rabbitmqctl add_user genie genie123'

        - name: Add RabbitMQ permissions
          command: >
            podman exec -d rabbitmq bash -c 'rabbitmqctl set_permissions -p / genie ".*" ".*" ".*"'


    - name: MongoDB
      block:
        - name: Stop and remove MongoDB container if it exists
          shell: |
            if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w mongodb; then
              podman stop mongodb && podman rm mongodb;
            else
              echo "MongoDB container does not exist.";
            fi

        - name: Run MongoDB container
          command: >
            podman run --name mongodb -p 27017:27017 -d {{ mongodb_image }}


    - name: Log in to Quay on all VMs
      command: >
        podman login -u='{{ registry_user }}' -p='{{ registry_password }}' quay.io

################################################################################################
- name: Deploy Reviewer containers
  hosts: reviewers
  gather_facts: no
  vars:
    reviewer_image: quay.io/rh-ee-yhabushi/tag/reviewer:2024.12.12
    reviewer_image_name: reviewer-service
    reviewer_container_name: reviewer-celery
    rabbitmq_port: "{{ RABBITMQ_PORT }}"
    rabbitmq_ip: "{{ RABBITMQ_IP }}"
    mongo_port: "{{ MONGO_PORT }}"
    mongo_ip: "{{ MONGO_IP }}"
    reviewer_model_id: "{{ REVIEWER_MODEL_HF_ID }}"
    reviewer_max_generation_length: "{{ REVIEWER_MAX_GENERATION_LENGTH }}"
    reviewer_max_context_length: "{{ REVIEWER_MAX_CONTEXT_LENGTH }}"
    reviewer_batch_size: "{{ REVIEWER_BATCH_SIZE }}"

  tasks:
    - name: Pull Reviewer image
      command: >
        podman pull {{ reviewer_image }}

    - name: Tag Reviewer image
      command: >
        podman tag {{ reviewer_image }} {{ reviewer_image_name }}

    - name: Stop and remove Reviewer container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ reviewer_container_name }}; then
          podman stop {{ reviewer_container_name }}  && podman rm {{ reviewer_container_name }};
        else
          echo "Reviewer container does not exist.";
        fi

    - name: Run Reviewer container
      command: >
        podman run -d \
            --name {{ reviewer_container_name }} \
            --net=host \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e REVIEWER_MODEL_HF_ID={{ reviewer_model_id }} \
            -e REVIEWER_MAX_GENERATION_LENGTH={{ reviewer_max_generation_length }} \
            -e REVIEWER_MAX_CONTEXT_LENGTH={{ reviewer_max_context_length }} \
            -e REVIEWER_BATCH_SIZE={{ reviewer_batch_size }} \
            {{ reviewer_image_name }} reviewer

################################################################################################
- name: Deploy Prompt Lab Submitter Container
  hosts: prompt_lab_submitter
  gather_facts: no
  vars:
    prompt_lab_image: quay.io/rh-ee-yhabushi/tag/prompt_lab:2024.12.12
    prompt_lab_image_name: promptlab-service
    prompt_lab_submitter_container_name: promptlab-submitter
    rabbitmq_port: "{{ RABBITMQ_PORT }}"
    rabbitmq_ip: "{{ RABBITMQ_IP }}"
    mongo_port: "{{ MONGO_PORT }}"
    mongo_ip: "{{ MONGO_IP }}"
    input_json_path: "{{ INPUT_JSON_PATH }}"
    output_data_dir_path: "{{ OUTPUT_DATA_DIR_PATH }}"
    prompt_lab_model_hf_id: "{{ PROMPT_LAB_MODEL_HF_ID }}"
    prompt_lab_max_generation_length: "{{ PROMPT_LAB_MAX_GENERATION_LENGTH }}"
    prompt_lab_max_context_length: "{{ PROMPT_LAB_MAX_CONTEXT_LENGTH }}"
    prompt_lab_batch_size: "{{ PROMPT_LAB_BATCH_SIZE }}"
    queue_target_size: "{{ QUEUE_TARGET_SIZE }}"
    template_name: "{{ TEMPLATE_NAME }}"
    template_agent: "{{ TEMPLATE_AGENT }}"
    template_type: "{{ TEMPLATE_TYPE }}"

  tasks:
    - name: Pull Prompt Lab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_submitter_container_name }}; then
          podman stop {{ prompt_lab_submitter_container_name }}  && podman rm {{ prompt_lab_submitter_container_name }};
        else
          echo "Promptlab submitter container does not exist.";
        fi

    - name: create output dir
      file:
        path: "{{ output_data_dir_path }}"
        state: directory
        mode: '777'

    - name: Run Prompt Lab container
      command: >
        podman run -d \
            --name {{ prompt_lab_submitter_container_name }} \
            --net=host \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e INPUT_JSON_PATH={{ input_json_path }} \
            -e OUTPUT_DATA_DIR_PATH={{ output_data_dir_path }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -v /home/instruct/{{ input_json_path }}:/app/repo/prompt_lab/{{ input_json_path }}:z \
            -v /home/instruct/{{ output_data_dir_path }}:/app/repo/prompt_lab/data:z \
            -v /home/instruct/{{ template_name }}:/app/repo/prompt_lab/{{ template_name }}:z \
            {{ prompt_lab_image_name }} prompt_submiter

################################################################################################
- name: Deploy Prompt Lab Dispatcher Container
  hosts: prompt_lab_dispatcher
  gather_facts: no
  vars:
    prompt_lab_image: quay.io/rh-ee-yhabushi/tag/prompt_lab:2024.12.12
    prompt_lab_image_name: promptlab-service
    prompt_lab_dispatcher_container_name: promptlab-dispatcher
    rabbitmq_port: "{{ RABBITMQ_PORT }}"
    rabbitmq_ip: "{{ RABBITMQ_IP }}"
    mongo_port: "{{ MONGO_PORT }}"
    mongo_ip: "{{ MONGO_IP }}"
    output_data_dir_path: "{{ OUTPUT_DATA_DIR_PATH }}"
    input_json_path: "{{ INPUT_JSON_PATH }}"
    prompt_lab_model_hf_id: "{{ PROMPT_LAB_MODEL_HF_ID }}"
    prompt_lab_max_generation_length: "{{ PROMPT_LAB_MAX_GENERATION_LENGTH }}"
    prompt_lab_max_context_length: "{{ PROMPT_LAB_MAX_CONTEXT_LENGTH }}"
    prompt_lab_batch_size: "{{ PROMPT_LAB_BATCH_SIZE }}"
    queue_target_size: "{{ QUEUE_TARGET_SIZE }}"
    template_name: "{{ TEMPLATE_NAME }}"
    template_agent: "{{ TEMPLATE_AGENT }}"
    template_type: "{{ TEMPLATE_TYPE }}"

  tasks:
    - name: Pull Prompt Lab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_dispatcher_container_name }}; then
          podman stop {{ prompt_lab_dispatcher_container_name }}  && podman rm {{ prompt_lab_dispatcher_container_name }};
        else
          echo "Promptlab dispatcher container does not exist.";
        fi

    - name: create output dir
      file:
        path: "{{ output_data_dir_path }}"
        state: directory
        mode: '777'

    - name: Run Prompt Lab container
      command: >
        podman run -d \
            --name {{ prompt_lab_dispatcher_container_name }} \
            --net=host \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e INPUT_JSON_PATH={{ input_json_path }} \
            -e OUTPUT_DATA_DIR_PATH={{ output_data_dir_path }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -v /home/instruct/{{ input_json_path }}:/app/repo/prompt_lab/{{ input_json_path }}:z \
            -v /home/instruct/{{ output_data_dir_path }}:/app/repo/prompt_lab/data:z \
            {{ prompt_lab_image_name }} prompt_dispatcher


################################################################################################
- name: Deploy Prompt Lab Dispatcher Worker
  hosts: prompt_lab_worker
  gather_facts: no
  vars:
    prompt_lab_image: quay.io/rh-ee-yhabushi/tag/prompt_lab:2024.12.12
    prompt_lab_image_name: promptlab-service
    prompt_lab_worker_container_name: promptlab-worker
    rabbitmq_port: "{{ RABBITMQ_PORT }}"
    rabbitmq_ip: "{{ RABBITMQ_IP }}"
    mongo_port: "{{ MONGO_PORT }}"
    mongo_ip: "{{ MONGO_IP }}"
    output_data_dir_path: "{{ OUTPUT_DATA_DIR_PATH }}"
    input_json_path: "{{ INPUT_JSON_PATH }}"
    prompt_lab_model_hf_id: "{{ PROMPT_LAB_MODEL_HF_ID }}"
    prompt_lab_max_generation_length: "{{ PROMPT_LAB_MAX_GENERATION_LENGTH }}"
    prompt_lab_max_context_length: "{{ PROMPT_LAB_MAX_CONTEXT_LENGTH }}"
    prompt_lab_batch_size: "{{ PROMPT_LAB_BATCH_SIZE }}"
    queue_target_size: "{{ QUEUE_TARGET_SIZE }}"
    template_name: "{{ TEMPLATE_NAME }}"
    template_agent: "{{ TEMPLATE_AGENT }}"
    template_type: "{{ TEMPLATE_TYPE }}"


  tasks:
    - name: Pull Prompt Lab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_worker_container_name }}; then
          podman stop {{ prompt_lab_worker_container_name }}  && podman rm {{ prompt_lab_worker_container_name }};
        else
          echo "Promptlab worker container does not exist.";
        fi

    - name: Run Prompt Lab container
      command: >
        podman run -d \
            --name {{ prompt_lab_worker_container_name }} \
            --net=host \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e INPUT_JSON_PATH={{ input_json_path }} \
            -e OUTPUT_DATA_DIR_PATH={{ output_data_dir_path }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -v /home/instruct/{{ input_json_path }}:/app/repo/prompt_lab/{{ input_json_path }}:z \
            -v /home/instruct/{{ output_data_dir_path }}:/app/repo/prompt_lab/data:z \
            {{ prompt_lab_image_name }} prompt_processor
