---
- name: Deploy containers on VMs
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Install Hugging Face CLI
      pip:
        name: huggingface_hub
        state: latest

    - name: Login to Hugging Face CLI
      shell: huggingface-cli login --token {{ hf_token }}
      register: huggingface_login
      ignore_errors: yes

    - name: Install vllm with pip
      pip:
        name: vllm
        state: latest
      register: vllm_install

    - name: RabbitMQ
      when: "'controller' in group_names"
      block:
        - name: Kill unneeded service
          become: yes
          command: >
            sudo systemctl stop showroom.service

        - name: Stop and remove RabbitMQ container if it exists$
          shell: |
            if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w rabbitmq; then
              podman rm -f rabbitmq;
            else
              echo "RabbitMQ container does not exist.";
            fi

        - name: Run RabbitMQ Container
          command: >
            podman run -d --name rabbitmq -h rabbitmq -p {{ rabbitmq_port }}:5672 -p 15672:15672 {{ rabbitmq_image }}


        - name: Wait for RabbitMQ container to be running
          shell: podman ps | grep rabbitmq
          register: rabbitmq_container
          retries: 5
          delay: 5
          until: rabbitmq_container.rc == 0

        - name: Check RabbitMQ application status
          shell: podman exec rabbitmq rabbitmqctl status
          register: rabbitmq_status
          retries: 5
          delay: 10
          until: rabbitmq_status.rc == 0

        - name: Display RabbitMQ port check result
          debug:
            msg: "RabbitMQ is up and listening on port {{ rabbitmq_port }}"

        - name: Add RabbitMQ user name
          command: >
            podman exec -d rabbitmq bash -c 'rabbitmqctl add_user genie genie123'

        - name: Add RabbitMQ permissions
          command: >
            podman exec -d rabbitmq bash -c 'rabbitmqctl set_permissions -p / genie ".*" ".*" ".*"'


        - name: MongoDB
          block:
            - name: Stop and remove MongoDB container if it exists
              shell: |
                if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w mongodb; then
                  podman stop mongodb && podman rm mongodb;
                else
                  echo "MongoDB container does not exist.";
                fi

            - name: Run MongoDB container
              command: >
                podman run --name mongodb -p {{mongo_port}}:27017 -d {{ mongodb_image }}


    - name: Log in to Quay on all VMs
      command: >
        podman login -u='{{ registry_user }}' -p='{{ registry_password }}' quay.io

################################################################################################
- name: Deploy Reviewer containers
  hosts: reviewers
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:

    - name: Kill tmux session 
      shell: tmux kill-session -t vllm_server
      ignore_errors: true

    - name: Start tmux session
      shell: |
        tmux new-session -d -s vllm_server
      register: tmux_session_started

    - name: Send 'vllm serve' command to tmux session
      shell: |
        tmux send-keys -t vllm_server "vllm serve {{ reviewer_model_id }} --port 8000 --max-model-len {{ reviewer_max_context_length }}" C-m
      when: tmux_session_started.changed

    - name: Verify VLLM server health endpoint
      uri:
        url: "http://0.0.0.0:8000/health"
        return_content: no
        status_code: 200
      retries: 24
      delay: 10
      register: vllm_health_check
      until: vllm_health_check.status == 200

    - name: Pull Reviewer image
      command: >
        podman pull {{ reviewer_image }}

    - name: Tag Reviewer image
      command: >
        podman tag {{ reviewer_image }} {{ reviewer_image_name }}

    - name: Stop and remove Reviewer container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ reviewer_container_name }}; then
          podman stop {{ reviewer_container_name }}  && podman rm {{ reviewer_container_name }};
        else
          echo "Reviewer container does not exist.";
        fi

    - name: Run Reviewer container
      command: >
        podman run -d \
            --name {{ reviewer_container_name }} \
            --net=host \
            -e HF_TOKEN={{ hf_token }} \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e VLLM_IP=0.0.0.0 \
            -e VLLM_PORT=8000 \
            -e REVIEWER_MODEL_HF_ID={{ reviewer_model_id }} \
            -e REVIEWER_MAX_GENERATION_LENGTH={{ reviewer_max_generation_length }} \
            -e REVIEWER_MAX_CONTEXT_LENGTH={{ reviewer_max_context_length }} \
            -e REVIEWER_BATCH_SIZE={{ reviewer_batch_size }} \
            -e REVIEWER_SCORE_THRESHOLD={{ reviewer_score_threshold }} \
            {{ reviewer_image_name }} reviewer

################################################################################################
- name: Deploy Prompt Lab Orbiter Worker
  hosts: prompt_lab_orbiter
  gather_facts: no
  vars:
    prompt_lab_image_name: promptlab-service
    prompt_lab_orbiter_container_name: promptlab-orbiter
  vars_files:
    - vars.yml

  tasks:

    - name: Kill tmux session 
      shell: tmux kill-session -t vllm_server
      ignore_errors: true

    - name: Start tmux session
      shell: |
        tmux new-session -d -s vllm_server
      register: tmux_session_started

    - name: Send 'vllm serve' command to tmux session
      shell: |
        tmux send-keys -t vllm_server "vllm serve {{ prompt_lab_model_hf_id }} --port 8000 --max-model-len {{ prompt_lab_max_context_length }}" C-m
      when: tmux_session_started.changed

    - name: Verify VLLM server health endpoint
      uri:
        url: "http://0.0.0.0:8000/health"
        return_content: no
        status_code: 200
      retries: 24
      delay: 10
      register: vllm_health_check
      until: vllm_health_check.status == 200

    - name: Pull Prompt Lab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_orbiter_container_name }}; then
          podman stop {{ prompt_lab_orbiter_container_name }}  && podman rm {{ prompt_lab_orbiter_container_name }};
        else
          echo "Promptlab orbiter container does not exist.";
        fi

    - name: Run Prompt Lab container
      command: >
        podman run -d \
            --name {{ prompt_lab_orbiter_container_name }} \
            --net=host \
            -e HF_TOKEN={{ hf_token }} \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e VLLM_IP=0.0.0.0 \
            -e VLLM_PORT=8000 \
            -e MODEL_API_URL={{ model_api_url }} \
            -e INPUT_DATASET_REPO={{ input_dataset_repo }} \
            -e INPUT_DATASET_FILE_NAME={{ input_dataset_file_name }} \
            -e OUTPUT_DATASET_REPO={{ output_dataset_repo }} \
            -e OUTPUT_DATASET_FILE_NAME={{ output_dataset_file_name }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -e MAX_RETRY={{ max_retry }} \
            -e TEMPLATE_PROJECT_CONTEXT={{templates_project_context}} \
            -e PROJECT_ID={{project_id}} \
            -e PROJECT_REPO ={{project_repo}} \
            {{ prompt_lab_image_name }} orbiter --celery --reviewer --celery-worker-concurrency 4 --celery-worker-prefetch-count 2

################################################################################################
- name: Deploy Prompt Lab Dispatcher Container
  hosts: prompt_lab_landing
  gather_facts: no
  vars:
    prompt_lab_image_name: promptlab-service
    prompt_lab_landing_container_name: promptlab-landing
  vars_files:
    - vars.yml

  tasks:
    - name: Pull Promptlab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_landing_container_name }}; then
          podman stop {{ prompt_lab_landing_container_name }}  && podman rm {{ prompt_lab_landing_container_name }};
        else
          echo "Promptlab landing container does not exist.";
        fi

    - name: Run Prompt Lab container
      command: >
        podman run -d \
            --name {{ prompt_lab_landing_container_name }} \
            --net=host \
            -e HF_TOKEN={{ hf_token }} \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e INPUT_DATASET_REPO={{ input_dataset_repo }} \
            -e INPUT_DATASET_FILE_NAME={{ input_dataset_file_name }} \
            -e OUTPUT_DATASET_REPO={{ output_dataset_repo }} \
            -e OUTPUT_DATASET_FILE_NAME={{ output_dataset_file_name }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e MODEL_API_URL={{ model_api_url }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -e MAX_RETRY={{ max_retry }} \
            -e TEMPLATE_PROJECT_CONTEXT={{templates_project_context}} \
            -e PROJECT_ID={{project_id}} \
            -e PROJECT_REPO ={{project_repo}} \
            {{ prompt_lab_image_name }} landing --celery

################################################################################################
- name: Deploy Prompt Lab Launchpad Container
  hosts: prompt_lab_launchpad
  gather_facts: no
  vars:
    prompt_lab_image_name: promptlab-service
    prompt_lab_launchpad_container_name: promptlab-launchpad
  vars_files:
    - vars.yml
    
  tasks:
    - name: Pull Prompt Lab image
      command: >
        podman pull {{ prompt_lab_image }}

    - name: Tag Promptlab image
      command: >
        podman tag {{ prompt_lab_image }} {{ prompt_lab_image_name }}

    - name: Stop and remove promptlab container if it exists
      shell: |
        if podman ps -a --format "{{ '{{ .Names }}' }}" | grep -w {{ prompt_lab_launchpad_container_name }}; then
          podman stop {{ prompt_lab_launchpad_container_name }}  && podman rm {{ prompt_lab_launchpad_container_name }};
        else
          echo "Promptlab launchpad container does not exist.";
        fi

    - name: Run prompt_launchpad container
      command: >
        podman run -d \
            --name {{ prompt_lab_launchpad_container_name }} \
            --net=host \
            -e HF_TOKEN={{ hf_token }} \
            -e RABBITMQ_PORT={{ rabbitmq_port }} \
            -e RABBITMQ_IP={{ rabbitmq_ip }} \
            -e MONGODB_PORT={{ mongo_port }} \
            -e MONGODB_IP={{ mongo_ip }} \
            -e INPUT_DATASET_REPO={{ input_dataset_repo }} \
            -e INPUT_DATASET_FILE_NAME={{ input_dataset_file_name }} \
            -e OUTPUT_DATASET_REPO={{ output_dataset_repo }} \
            -e OUTPUT_DATASET_FILE_NAME={{ output_dataset_file_name }} \
            -e PROMPT_LAB_MODEL_HF_ID={{ prompt_lab_model_hf_id }} \
            -e PROMPT_LAB_MAX_GENERATION_LENGTH={{ prompt_lab_max_generation_length }} \
            -e PROMPT_LAB_MAX_CONTEXT_LENGTH={{ prompt_lab_max_context_length }} \
            -e PROMPT_LAB_BATCH_SIZE={{ prompt_lab_batch_size }} \
            -e QUEUE_TARGET_SIZE={{ queue_target_size }} \
            -e MODEL_API_URL={{ model_api_url }} \
            -e TEMPLATE_NAME={{ template_name }} \
            -e TEMPLATE_AGENT={{ template_agent }} \
            -e TEMPLATE_TYPE={{ template_type }} \
            -e MAX_RETRY={{ max_retry }} \
            -e TEMPLATE_PROJECT_CONTEXT={{templates_project_context}} \
            -e PROJECT_ID={{project_id}} \
            -e PROJECT_REPO ={{project_repo}} \
            {{ prompt_lab_image_name }} launchpad
