location ~ ^/api/backend/(.*|$) {
    #proxy_pass http://genie-llm-be:8080;
    proxy_pass http://$LLM_BE_URL;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location ~ ^/api/(.*|$) {
    #proxy_pass http://genie-be:8080;
    proxy_pass http://$BE_URL;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

