name: Backup Databases

env:
  PREPROD_API: "https://api.stc-ai-e1-pp.imap.p1.openshiftapps.com:6443"
  PROD_API: "https://api.stc-ai-e1-prod.rtc9.p1.openshiftapps.com:6443"
  MONGO_URI: "mongodb://localhost:27017/unifai"
  NAMESPACE: "tag-ai--pipeline"
  MONGO_POD: "mongodb-0"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:                
    branches: [ "GENIE-1071/backup_dbs" ]

jobs:
  backup_mongo:
    runs-on: ubuntu-latest
    steps:

      - name: Check MongoDB Connection
        run: |
          # kubectl login $PREPROD_API --token=$PP_CLUSTER 
          kubectl config set-credentials preprod --token=$PP_CLUSTER
          kubectl config set-cluster preprod --server=$PREPROD_API
          kubectl config set-context preprod --user=preprod --cluster=preprod
          kubectl config use-context preprod
          kubectl get pods --namespace $NAMESPACE
          kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- mongo --eval "db.adminCommand('ping')"
      
      - name: Backup MongoDB
        run: |
          kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- mongodump --uri="mongodb://localhost:27017/unifai" --out="/tmp/backup"
          tar -czvf /tmp/backup.tar.gz /tmp/backup
          #aws s3 cp /tmp/backup.tar.gz s3://unifai-backup/backup.tar.gz
          echo "Backup completed"
          echo "Removing temporary files"
          rm -rf /tmp/backup
          rm /tmp/backup.tar.gz
          echo "Temporary files removed"
          echo "Backup completed"