name: Backup Databases

env:
  # PREPROD_API: "https://api.stc-ai-e1-pp.imap.p1.openshiftapps.com:6443"
  # PROD_API: "https://api.stc-ai-e1-prod.rtc9.p1.openshiftapps.com:6443"
  #MONGO_URI: "mongodb://localhost:27017/unifai"
  NAMESPACE: ${{ vars.NAMESPACE }}
  MONGO_POD: "mongodb-0"
  username: "tag-ai"
  #cluster_name: "PP"
  #cluster_secret: ${{ secrets.PP_CLUSTER }}
  BACKUP_REPO: ${{ vars.BACKUP_REPO_URL }}
  #BACKUP_REPO: "https://${{ secrets.GITLAB_BACKUP_REPO_KEY }}@gitlab.cee.redhat.com/ai_tools/unifai_backups.git"
  BACKUP_REPO_NAME: ${{ vars.BACKUP_REPO_NAME }}

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Which branch do you want to use?'
        required: true
        default: 'GENIE-1071/backup_dbs'
      target_cluster:
        description: 'Which cluster do you want to backup?'
        required: true
        default: 'PRE-PRODUCTION'
      target_namespace:
        description: 'Which namespace do you want to backup?'
        required: true
        default: 'tag-ai--pipeline'
  #This triggers the workflow automatically anytime someone pushes to the branch - needs to change to when this file is changed
  push:                
    branches: [ 'GENIE-1071/backup_dbs' ]
    paths: [ '.github/workflows/backup-dbs.yaml', '.github/scripts/qdrant_backup.py' ]

jobs:

  verify_agent_deps:
    uses: ./.github/workflows/verify-agent-deps.yaml

  backup_mongo:
    runs-on: linux
    needs: verify_agent_deps
    environment:
      name: ${{ inputs.target_cluster }}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.target_branch }}

      - name: Verify Secret isn't empty
        run: |
          if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
            echo "SECRET IS EMPTY"
          else
            echo "Secret has a length of ${#cluster_secret} characters"
          fi

      - name: Check Cluster Connection
        run: | 
          echo cluster_secret: ${{ secrets.ACCESS_TOKEN }}
          kubectl config set-credentials ${{ inputs.target_cluster }} --token=${{ secrets.ACCESS_TOKEN }}
          kubectl config set-cluster ${{ inputs.target_cluster }} --server=${{ vars.API_URL }}
          #here we combine the credentials and the cluster url to create a context, both has the same name.
          kubectl config set-context ${{ inputs.target_cluster }} --user=${{ inputs.target_cluster }} --cluster=${{ inputs.target_cluster }}
          kubectl config use-context ${{ inputs.target_cluster }}
          kubectl get pods --namespace ${{ inputs.target_namespace }}
          kubectl get deployments --namespace ${{ inputs.target_namespace }}
      
      - name: Backup MongoDB
        run: |
          echo "Removing old backup files"
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- rm -rf /tmp/backup
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- rm -rf /tmp/backup.tar.gz
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- mongodump --uri="${{ vars.MONGO_URI }}" --out="/tmp/backup"
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- ls -la /tmp/backup
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- tar -czvf /tmp/backup.tar.gz /tmp/backup
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- ls -la /tmp/backup.tar.gz
          kubectl cp --namespace ${{ inputs.target_namespace }} $MONGO_POD:/tmp/backup.tar.gz /tmp/backup.tar.gz
          ls -la /tmp/backup.tar.gz
          echo "Removing temporary files"
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- rm -rf /tmp/backup
          kubectl exec --namespace ${{ inputs.target_namespace }} $MONGO_POD -- rm -rf /tmp/backup.tar.gz
          echo "Temporary files removed"
          echo "Backup completed"

  backup_qdrant:
    runs-on: linux
    needs: verify_agent_deps
    environment:
      name: ${{ inputs.target_cluster }}
    steps:

      - name: Backup Qdrant
        run: |
          echo "Backing up Qdrant"
          python .github/scripts/qdrant_backup.py
          echo "Qdrant backup completed"

  upload_to_gitlab:        
    runs-on: linux
    needs: 
      - backup_qdrant
      - backup_mongo
    steps:

      - name: Upload files to gitlab repo
        run: |

          git clone $BACKUP_REPO
          cp /tmp/backup.tar.gz $BACKUP_REPO_NAME/
          cp -r snapshots $BACKUP_REPO_NAME/

          cd $BACKUP_REPO_NAME
          git config user.email "sfiresht@redhat.com"
          git config user.name "sfiresht"
          git add .
          git commit -m "uploading backup files to gitlab"
          echo "Committed changes"
          git push
        shell: bash        