name: Backup Databases

env:
  PREPROD_API: "https://api.stc-ai-e1-pp.imap.p1.openshiftapps.com:6443"
  PROD_API: "https://api.stc-ai-e1-prod.rtc9.p1.openshiftapps.com:6443"
  MONGO_URI: "mongodb://localhost:27017/unifai"
  NAMESPACE: tag-ai--pipeline
  MONGO_POD: "mongodb-0"
  username: "tag-ai"
  cluster_name: "PP"
  cluster_secret: ${{ secrets.PP_CLUSTER }}

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Which branch do you want to use?'
        required: true
        default: 'GENIE-1071/backup_dbs'
      target_cluster:
        description: 'Which cluster do you want to backup?'
        required: true
        default: 'PP'
      target_namespace:
        description: 'Which namespace do you want to backup?'
        required: true
        default: 'tag-ai--pipeline'
  #This triggers the workflow automatically anytime someone pushes to the branch - needs to change to when this file is changed
  push:                
    branches: [ 'GENIE-1071/backup_dbs' ]
    paths: [ '.github/workflows/backup-dbs.yaml' ]

jobs:

  verify_agent_deps:
    uses: ./.github/workflows/verify-agent-deps.yaml

  backup_mongo:
    runs-on: linux
    needs: verify_agent_deps
    steps:
# THIS IS THE VITAL STEP:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.target_branch }}

      - name: Verify Secret isn't empty
        run: |
          if [ -z "$cluster_secret" ]; then
            echo "SECRET IS EMPTY"
          else
            echo "Secret has a length of ${#cluster_secret} characters"
          fi

      # - name: Check Cluster Connection
      #   run: | 
      #     echo "cluster_secret: $cluster_secret"
      #     kubectl config set-credentials $cluster_name --token=$cluster_secret
      #     kubectl config set-cluster $cluster_name --server=$PREPROD_API
      #     kubectl config set-context $cluster_name --user=$cluster_name --cluster=$cluster_name
      #     kubectl config use-context $cluster_name
      #     kubectl get pods --namespace $NAMESPACE
      #     kubectl get deployments --namespace $NAMESPACE
      #     #kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- mongo --eval "db.adminCommand('ping')"
      
      # - name: Backup MongoDB
      #   run: |
      #     echo "Removing old backup files"
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- rm -rf /tmp/backup
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- rm -rf /tmp/backup.tar.gz
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- mongodump --uri="mongodb://localhost:27017" --out="/tmp/backup"
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- ls -la /tmp/backup
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- tar -czvf /tmp/backup.tar.gz /tmp/backup
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- ls -la /tmp/backup.tar.gz
      #     kubectl cp --namespace $NAMESPACE $MONGO_POD:/tmp/backup.tar.gz /tmp/backup.tar.gz
      #     ls -la /tmp/backup.tar.gz
      #     echo "Removing temporary files"
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- rm -rf /tmp/backup
      #     kubectl exec --namespace $NAMESPACE -it $MONGO_POD -- rm -rf /tmp/backup.tar.gz
      #     echo "Temporary files removed"
      #     echo "Backup completed"

      - name: Backup Qdrant
        run: |
          echo "Backing up Qdrant"
          python .github/scripts/qdrant_backup.py
          echo "Qdrant backup completed"
